### ISSUE TITLE
Gatling load test failing on Ubuntu 16.04

### ISSUE THREAD

**Issue by guilhebl** [playframework/play-scala-rest-api-example#71]
Just cloned and tried running gatling test following steps provided on README, 
local repository is exactly the same as version from origin/2.5.x

when running `sbt gatling:test` I get:

```
[error] Uncaught exception when running simulation.GatlingSpec: java.lang.NoSuchMethodError: org.asynchttpclient.netty.channel.DefaultChannelPool.<init>(IILio/netty/util/Timer;)V
sbt.ForkMain$ForkError: java.lang.NoSuchMethodError: org.asynchttpclient.netty.channel.DefaultChannelPool.<init>(IILio/netty/util/Timer;)V
	at io.gatling.http.ahc.DefaultAhcFactory.newChannelPool(AhcFactory.scala:84)
	at io.gatling.http.ahc.DefaultAhcFactory.<init>(AhcFactory.scala:143)
```

OS: Linux Ubuntu 16.04
Java: 1.8.0_131

**Comment by wsargent** [comment]
Looks like gatling's underlying asynchttpclient is conflicting with Play's.  Upgrading.
