### ISSUE TITLE
FileNotFoundException

### ISSUE THREAD

**Issue by eed3si9n** [playframework/play-scala-rest-api-example#91]
On Tech Hub, I am seeing FileNotFoundException:

```
[info] [play-rest-api] java.io.FileNotFoundException: /home/ubuntu/workspace/techhub-publisher/label/techhub-ci/target/clones/play-rest-api/docs/target/streams/compile/paradoxThemeDirectory/$global/streams (Is a directory)
[info] [play-rest-api] 	at java.io.FileOutputStream.open0(Native Method)
[info] [play-rest-api] 	at java.io.FileOutputStream.open(FileOutputStream.java:270)
[info] [play-rest-api] 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
[info] [play-rest-api] 	at sbt.Using$$anonfun$fileOutputStream$1.apply(Using.scala:72)
[info] [play-rest-api] 	at sbt.Using$$anonfun$fileOutputStream$1.apply(Using.scala:72)
[info] [play-rest-api] 	at sbt.Using$$anon$2.openImpl(Using.scala:65)
[info] [play-rest-api] 	at sbt.OpenFile$class.open(Using.scala:43)
[info] [play-rest-api] 	at sbt.Using$$anon$2.open(Using.scala:64)
[info] [play-rest-api] 	at sbt.Using$$anon$2.open(Using.scala:64)
[info] [play-rest-api] 	at sbt.Using.apply(Using.scala:23)
[info] [play-rest-api] 	at sbt.IO$.gzipFileOut(IO.scala:864)
[info] [play-rest-api] 	at sbt.Sync$.writeInfo(Sync.scala:77)
[info] [play-rest-api] 	at sbt.Sync$$anonfun$apply$1.apply(Sync.scala:45)
[info] [play-rest-api] 	at sbt.Sync$$anonfun$apply$1.apply(Sync.scala:22)
[info] [play-rest-api] 	at com.typesafe.sbt.web.SbtWeb$.syncMappings(SbtWeb.scala:532)
[info] [play-rest-api] 	at com.lightbend.paradox.sbt.ParadoxPlugin$$anonfun$paradoxSettings$23.apply(ParadoxPlugin.scala:101)
[info] [play-rest-api] 	at com.lightbend.paradox.sbt.ParadoxPlugin$$anonfun$paradoxSettings$23.apply(ParadoxPlugin.scala:101)
[info] [play-rest-api] 	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
[info] [play-rest-api] 	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
[info] [play-rest-api] 	at sbt.std.Transform$$anon$4.work(System.scala:63)
[info] [play-rest-api] 	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[info] [play-rest-api] 	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[info] [play-rest-api] 	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[info] [play-rest-api] 	at sbt.Execute.work(Execute.scala:237)
[info] [play-rest-api] 	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[info] [play-rest-api] 	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[info] [play-rest-api] 	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
[info] [play-rest-api] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
[info] [play-rest-api] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info] [play-rest-api] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[info] [play-rest-api] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info] [play-rest-api] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info] [play-rest-api] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[info] [play-rest-api] 	at java.lang.Thread.run(Thread.java:748)
[info] [play-rest-api] [error] (docs/compile:paradoxThemeDirectory) java.io.FileNotFoundException: /home/ubuntu/workspace/techhub-publisher/label/techhub-ci/target/clones/play-rest-api/docs/target/streams/compile/paradoxThemeDirectory/$global/streams (Is a directory)
[info] [play-rest-api] [error] Total time: 1 s, completed Oct 25, 2017 9:48:32 PM
```

**Comment by eed3si9n** [comment]
Fixed in https://github.com/playframework/play-scala-rest-api-example/commit/b298f6762aaebdc489e3d8328ebd0a7371c74a22
