### ISSUE TITLE
Error when running gatling test

### ISSUE THREAD

**Issue by pebert** [playframework/play-scala-rest-api-example#94]
After doing a clone and following through the readme everything works except gatling throws an error after running "sbt gatling:test"

All I could find online was this pastebin https://pastebin.com/byJechzK with the same problem but no solution.

Compiling 1 Scala source to /path/to/play-scala-rest-api-example/target/scala-2.11/gatling-classes ...
Done compiling.
java.lang.NumberFormatException: null
 	at java.lang.Integer.parseInt(Integer.java:542)
 	at java.lang.Integer.parseInt(Integer.java:615)
 	at org.asynchttpclient.config.AsyncHttpClientConfigHelper$Config.getInt(AsyncHttpClientConfigHelper.java:85)
 	at org.asynchttpclient.config.AsyncHttpClientConfigDefaults.defaultMaxRedirects(AsyncHttpClientConfigDefaults.java:59)
 	at org.asynchttpclient.DefaultAsyncHttpClientConfig$Builder.<init>(DefaultAsyncHttpClientConfig.java:582)
 	at io.gatling.http.ahc.DefaultAhcFactory.newAhcConfigBuilder(AhcFactory.scala:89)
 	at io.gatling.http.ahc.DefaultAhcFactory.<init>(AhcFactory.scala:144)
 	at io.gatling.http.ahc.AhcFactory$.apply(AhcFactory.scala:46)
 	at io.gatling.http.ahc.HttpEngine$.apply(HttpEngine.scala:40)
 	at io.gatling.http.protocol.HttpProtocol$$anon$1.newComponents(HttpProtocol.scala:52)
 	at io.gatling.core.protocol.ProtocolComponentsRegistry.io$gatling$core$protocol$ProtocolComponentsRegistry$$$anonfun$1(Protocol.scala:57)

**Comment by marcospereira** [comment]
Thanks for reporting that, @pebert.

Problem is that this project is depending on scalatestplus-play 3.0.0-M3 which [depends on play-ws 2.6.0-M4](http://mvnrepository.com/artifact/org.scalatestplus.play/scalatestplus-play_2.12/3.0.0-M3). And play-ws has the following problem:

https://github.com/playframework/playframework/issues/7056
https://github.com/playframework/play-ws/issues/87

So, we just need to update scalatestplus-play to the latest version here.
